# # Basic way — open, read, close
# file = open("sample.txt", "r")   # "r" = read mode
# content = file.read()
# file.close()                      # always close!

# print(content)



# "with" automatically closes the file — even if an error occurs!
# with open("sample.txt", "r") as file:
#     content = file.read()

# print(content)
# print(type(content))   # <class 'str'> — it's just a big string!

# Read all lines into a list
# with open("sample.txt", "r") as file:
#     lines = file.readlines()   # returns a list of strings

# print(f"Total lines: {len(lines)}")

# for i, line in enumerate(lines):
#     print(f"Line {i}: {line.strip()}")  # .strip() removes \n at end


# "w" = write mode (creates file if not exists, OVERWRITES if exists!)
# with open("output.txt", "w") as file:
#     file.write("This is the LLM response.\n")
#     file.write("Generated by our Gen AI app.\n")

# print("✅ File written!")

# # "a" = append mode (adds to end, doesn't overwrite)
# with open("output.txt", "a") as file:
#     file.write("This line was appended.\n")

# print("✅ Line appended!")


import json

# In a chatbot, you want to save the conversation
conversation = [
    {"role": "user", "content": "What is RAG?"},
    {"role": "assistant", "content": "RAG stands for Retrieval Augmented Generation."},
    {"role": "user", "content": "How does it work?"},
]

# Save as JSON file
# with open("conversation_history.json", "w") as file:
#     json.dump(conversation, file, indent=2)

# print("✅ Conversation saved!")

# # Load it back
# with open("conversation_history.json", "r") as file:
#     loaded = json.load(file)

# print(f"Loaded {len(loaded)} messages")
# for message in loaded:
#     print(f"{message['role']}: {message['content']}")


# This is the FIRST step in any RAG pipeline
# Load a document → clean it → split into chunks

# def load_document(filepath):
#     # Check file exists first
#     try:
#         with open(filepath, "r", encoding="utf-8") as file:
#             content = file.read()
#         return content
#     except FileNotFoundError:
#         return None

# def split_into_chunks(text, chunk_size=100):
#     words = text.split()               # split into words
#     chunks = []
    
#     for i in range(0, len(words), chunk_size):
#         chunk = " ".join(words[i:i + chunk_size])
#         chunks.append(chunk)
    
#     return chunks

# # Run the pipeline
# content = load_document("sample.txt")

# if content:
#     print(f"✅ Loaded document — {len(content)} characters")
#     chunks = split_into_chunks(content, chunk_size=10)
#     print(f"✅ Split into {len(chunks)} chunks\n")
    
#     for i, chunk in enumerate(chunks):
#         print(f"Chunk {i}: {chunk}")
# else:
#     print("❌ File not found!")


# EXERCISE — Conversation Logger
# Build a system that saves and loads chatbot conversations
# This is used in every production chatbot!

import json

def save_conversation(messages, filename):
    with open(filename, "w") as file:        # ✅ auto-closes
        json.dump(messages, file, indent=2)
    return f"✅ Saved {len(messages)} messages to {filename}"

def load_conversation(filename):
    try:
        with open(filename, "r") as file:    # ✅ auto-closes
            return json.load(file)
    except FileNotFoundError:
        return []

    # If file doesn't exist return an empty list []
    # Hint: try/except FileNotFoundError
    # YOUR CODE HERE

def add_message(messages, role, content):
    # TASK 3: Append a new dict with "role" and "content" to messages
    new_message = {"role": role, "content": content}
    messages.append(new_message)
    return messages
    # Return the updated messages list
    # YOUR CODE HERE


# Test it
chat = []

# Add some messages
chat = add_message(chat, "user", "What is LangChain?")
chat = add_message(chat, "assistant", "LangChain is a framework for LLM apps.")
chat = add_message(chat, "user", "What is RAG?")

# Save to file
print(save_conversation(chat, "test_chat.json"))

# Load it back
loaded_chat = load_conversation("test_chat.json")
print(f"Loaded {len(loaded_chat)} messages")

# Try loading a file that doesn't exist
empty = load_conversation("doesnt_exist.json")
print(f"Missing file returned: {empty}")